# -*- coding: utf-8 -*-
"""LegalRAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17wTogQfpb3Xed9g65EtVyUHVHyEiJ58D
"""

!pip install -q langchain-community spacy
!python -m spacy download en_core_web_sm

import re
import spacy

nlp = spacy.load("en_core_web_sm")

# Words that spaCy misidentifies as ORG/PERSON in legal text
LEGAL_NOISE_WORDS = {
    "party", "effective date", "definitions", "suite", "deliverab",
    "the service provider", "this master services agreement", "agreement",
    "section", "schedule", "exhibit", "innovation plaza"
}

def clean_parties(raw_entities):
    cleaned = []
    for ent in raw_entities:
        ent_clean = ent.strip()
        # Filter out short terms, legal noise words, and title-case section headers
        if (
            len(ent_clean) > 3
            and ent_clean.lower() not in LEGAL_NOISE_WORDS
            and not ent_clean.isupper()  # Filters out "DEFINITIONS"
        ):
            cleaned.append(ent_clean)

    # Deduplicate entries where one is a substring of another (e.g., keep "Atharva Pvt. Ltd." over "Atharva Pvt")
    final_parties = []
    for p in sorted(cleaned, key=len, reverse=True):
        if not any(p in existing for existing in final_parties):
            final_parties.append(p)

    return final_parties

def extract_refined_metadata(file_path):
    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()

    # 1. Extract Entities from the first 1200 characters (Document Header)
    header_text = text[:1200]
    doc = nlp(header_text)
    raw_entities = [ent.text.strip() for ent in doc.ents if ent.label_ in ["ORG", "PERSON"]]

    # Clean the extracted parties
    parties = clean_parties(raw_entities)

    # 2. Extract Document Type
    doc_type = "General Legal Document"
    if re.search(r"non-disclosure agreement|\bnda\b", text, re.IGNORECASE):
        doc_type = "NDA"
    elif re.search(r"master services agreement|\bmsa\b", text, re.IGNORECASE):
        doc_type = "MSA"
    elif re.search(r"employment agreement|employment contract", text, re.IGNORECASE):
        doc_type = "Employment Agreement"

    # 3. Extract Primary Effective Date
    effective_date_match = re.search(
        r"(?:effective|entered into|dated as of)\s+(?:on\s+)?(\b\d{4}-\d{2}-\d{2}\b|\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+\d{4}\b)",
        text,
        re.IGNORECASE
    )

    all_dates = list(set(re.findall(
        r"(\b\d{4}-\d{2}-\d{2}\b|\b(?:January|February|March|April|May|June|July|August|September|October|November|December)\s+\d{1,2},\s+\d{4}\b)",
        text,
        re.IGNORECASE
    )))

    primary_date = effective_date_match.group(1) if effective_date_match else (all_dates[0] if all_dates else "Unknown")

    global_metadata = {
        "doc_type": doc_type,
        "primary_parties": parties,
        "effective_date": primary_date,
        "total_dates_found": len(all_dates),
        "source_file": file_path
    }

    return text, global_metadata

# Run updated extraction
raw_text, doc_metadata = extract_refined_metadata("legal.txt")

print("--- Cleaned Global Metadata ---")
for key, value in doc_metadata.items():
    print(f"{key}: {value}")

from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document

# 1. Initialize the Text Splitter
# 800 characters per chunk with 150 character overlap keeps legal clauses intact
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=800,
    chunk_overlap=150,
    separators=["\n\n", "\n", " ", ""]
)

# 2. Split the raw document text into chunks
raw_chunks = text_splitter.split_text(raw_text)

# 3. Create Document Objects with Inherited Metadata
chunked_documents = []

for idx, chunk_str in enumerate(raw_chunks):
    # Copy global metadata so each chunk gets its own independent dictionary
    chunk_metadata = doc_metadata.copy()

    # Add chunk-specific tracking IDs
    chunk_metadata["chunk_id"] = f"{doc_metadata['source_file']}_chunk_{idx}"
    chunk_metadata["chunk_index"] = idx

    # Create LangChain Document object
    doc = Document(
        page_content=chunk_str,
        metadata=chunk_metadata
    )
    chunked_documents.append(doc)

print(f" Total document split into {len(chunked_documents)} chunks.")
print("="*60)

# Preview Chunk 0
print(f"--- PREVIEW CHUNK 0 ---")
print(f"ID: {chunked_documents[0].metadata['chunk_id']}")
print(f"Inherited Metadata: {chunked_documents[0].metadata}")
print(f"Text Content:\n{chunked_documents[0].page_content[:200]}...")

print("\n" + "="*60)

# Preview Chunk 1
if len(chunked_documents) > 1:
    print(f"--- PREVIEW CHUNK 1 ---")
    print(f"ID: {chunked_documents[1].metadata['chunk_id']}")
    print(f"Inherited Metadata: {chunked_documents[1].metadata}")
    print(f"Text Content:\n{chunked_documents[1].page_content[:200]}...")

!pip install -q chromadb sentence-transformers langchain-huggingface

from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma

# 1. Load a fast, high-quality local embedding model
# This runs on your Colab GPU/CPU for free without API keys
print("Loading HuggingFace embedding model...")
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2",
    model_kwargs={"device": "cuda"} # Uses Colab GPU if available, falls back gracefully
)

# 2. Initialize ChromaDB and populate it with our chunked documents and metadata
print("Indexing chunks into ChromaDB...")
vectorstore = Chroma.from_documents(
    documents=chunked_documents,
    embedding=embeddings,
    collection_name="legal_contracts_demo"
)

print(f" Successfully indexed {vectorstore._collection.count()} chunks into ChromaDB!")

# 3. Test a fast similarity search query to confirm storage works
sample_query = "What are the rules regarding confidentiality or indemnification?"
matched_docs = vectorstore.similarity_search(sample_query, k=2)

print("\n" + "="*60)
print(f"--- SAMPLE VECTOR SEARCH TEST RESULT ---")
print(f"Query: '{sample_query}'\n")
for i, doc in enumerate(matched_docs):
    print(f"Result {i+1}:")
    print(f"Chunk ID: {doc.metadata['chunk_id']}")
    print(f"Inherited Parties: {doc.metadata['primary_parties']}")
    print(f"Content Snippet: {doc.page_content[:150]}...")
    print("-" * 40)

!pip install -q sentence-transformers

from sentence_transformers import CrossEncoder

# 1. Load a fast local Cross-Encoder model for reranking
print("Loading BAAI/bge-reranker-v2-m3 Cross-Encoder...")
reranker = CrossEncoder("BAAI/bge-reranker-v2-m3", max_length=512)

def retrieve_and_rerank(query, top_k_retrieval=10, top_k_rerank=3):
    print(f"\n--- Processing Query: '{query}' ---")

    # STAGE 1: Vector Search + Metadata Filtering (Retrieving candidate chunks)
    # ChromaDB similarity search gets candidate chunks
    initial_candidates = vectorstore.similarity_search(query, k=top_k_retrieval)
    print(f"Stage 1: Retrieved {len(initial_candidates)} candidate chunks via Vector Search.")

    # STAGE 2: Cross-Encoder Reranking
    # Prepare pairs for the Cross-Encoder: [[query, doc1_text], [query, doc2_text], ...]
    pairs = [[query, doc.page_content] for doc in initial_candidates]

    # Predict relevance scores (returns float scores for each candidate)
    scores = reranker.predict(pairs)

    # Attach scores to the documents and sort descending
    scored_docs = list(zip(initial_candidates, scores))
    scored_docs.sort(key=lambda x: x[1], reverse=True)

    # Select the top N reranked documents
    reranked_docs = [doc for doc, score in scored_docs[:top_k_rerank]]

    print(f"Stage 2: Reranked candidates and selected top {top_k_rerank} chunks.\n")

    # Display the top reranked chunks with scores
    for i, (doc, score) in enumerate(scored_docs[:top_k_rerank]):
        print(f"Rank {i+1} (Reranker Score: {score:.4f}):")
        print(f"  Chunk ID: {doc.metadata['chunk_id']}")
        print(f"  Parties: {doc.metadata['primary_parties']}")
        print(f"  Text: {doc.page_content[:180]}...\n")

    return reranked_docs

# Run a test query through the pipeline
test_query = "What happens in case of a confidentiality breach or data leak?"
top_context_chunks = retrieve_and_rerank(test_query, top_k_retrieval=10, top_k_rerank=3)

!pip install -q groq

import os
from groq import Groq

# 1. Set your Groq API key
# Get one for free at: https://console.groq.com/keys
os.environ["GROQ_API_KEY"] = ""


client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

def generate_rag_answer_groq(query, top_chunks):
    # Format context from reranked chunks with their inherited metadata
    formatted_context = ""
    for i, doc in enumerate(top_chunks):
        formatted_context += f"--- CONTEXT SNIPPET {i+1} ---\n"
        formatted_context += f"Source File: {doc.metadata.get('source_file')}\n"
        formatted_context += f"Contract Type: {doc.metadata.get('doc_type')}\n"
        formatted_context += f"Primary Parties: {', '.join(doc.metadata.get('primary_parties', []))}\n"
        formatted_context += f"Effective Date: {doc.metadata.get('effective_date')}\n"
        formatted_context += f"Content:\n{doc.page_content}\n\n"

    system_instruction = (
        "You are a helpful legal assistant. Answer the user's question using ONLY the provided text snippets and metadata. "
        "If the answer is not explicitly mentioned in the context, state 'I cannot find this information in the provided document.' "
        "Do not hallucinate or assume facts not present in the context."
    )

    user_prompt = f"""DOCUMENT CONTEXT:
{formatted_context}

USER QUESTION:
{query}
"""

    # Query Groq API using Llama-3.3 70B
    chat_completion = client.chat.completions.create(
        messages=[
            {"role": "system", "content": system_instruction},
            {"role": "user", "content": user_prompt},
        ],
        model="llama-3.3-70b-versatile",
        temperature=0.1,  # Low temperature for factual, deterministic legal answers
    )

    return chat_completion.choices[0].message.content

# Run End-to-End Test
user_question = "What happens if there is a breach of confidentiality or data leak, and who is involved?"

# 1. Retrieve & Rerank Chunks (from Step 7)
top_reranked_chunks = retrieve_and_rerank(user_question, top_k_retrieval=10, top_k_rerank=3)

# 2. Generate Final LLM Answer via Groq
final_answer = generate_rag_answer_groq(user_question, top_reranked_chunks)

print("="*60)
print("--- FINAL GROQ RAG PIPELINE ANSWER ---")
print(final_answer)
print("="*60)

!pip install -q ragas

from ragas import evaluate
from ragas.metrics import (
    faithfulness,
    answer_relevancy,
    context_precision,
    context_recall,
)
from datasets import Dataset

# 1. Prepare your evaluation dataset
eval_data = {
    "question": [
        "Who are the primary parties in the agreement?",
        "What is the effective date of the contract?"
    ],
    "contexts": [
        # List of string chunks retrieved by your pipeline for each question
        [["Atharva Pvt. Ltd. and Godbole Inc. enter into this agreement..."]],
        [["This Master Services Agreement is entered into on October 31, 2025..."]]
    ],
    "answer": [
        # Final answer produced by Groq
        "The primary parties are Atharva Pvt. Ltd. and Godbole Inc.",
        "The effective date of the agreement is October 31, 2025."
    ],
    "ground_truth": [
        # Expected reference answer
        "Atharva Pvt. Ltd. and Godbole Inc.",
        "October 31, 2025"
    ]
}

# 2. Convert to HuggingFace Dataset format
dataset = Dataset.from_dict(eval_data)

# 3. Compute metrics across the entire test set
results = evaluate(
    dataset=dataset,
    metrics=[
        faithfulness,       # Checks for hallucinations
        answer_relevancy,   # Checks if answer answers query
        context_precision,  # Checks if retrieved chunks are on-topic
        context_recall,     # Checks if all necessary context was retrieved
    ],
)

# Output evaluation dataframe
print("--- RAG Evaluation Scores ---")
print(results.to_pandas()[["faithfulness", "answer_relevancy", "context_precision", "context_recall"]])

!pip install -q "langchain-community<0.4.2" ragas

import sys
import types

# Create a dummy module for the deprecated langchain_community path
dummy_vertex = types.ModuleType("langchain_community.chat_models.vertexai")
dummy_vertex.ChatVertexAI = type("ChatVertexAI", (object,), {})

# Register it in sys.modules
sys.modules["langchain_community.chat_models.vertexai"] = dummy_vertex

print(" Missing module mocked successfully. Importing ragas...")

# Now import ragas
from ragas import evaluate
from ragas.metrics import faithfulness, answer_relevancy
print(" Ragas imported successfully!")

